---
# tasks file for roles/apache

- name: Install all neccesary packages for mariaDB.
  import_tasks: install.yml
# - name: Configure database.
#   import_tasks: configure-db.yml

- name: Configure apache.
  import_tasks: configure-apache.yml

- name: Configure webapp.
  import_tasks: configure-webapp.yml
