# databas: 172.28.128.135
# webb: 172.28.128.89

all:
  children:
    webservers:
      hosts:
        172.28.128.89:

    dbservers:
      hosts:
        172.28.128.135:

  vars:
    ansible_user: deploy
    ansible_ssh_private_key_file: ~/.ssh/deploy_id_rsa
    ansible_become: True
    ansible_become_user: root
    ansible_become_method: sudo
