---
# Configures webapp

- name: Pull webapp repository from github.
  ansible.builtin.git:
    repo: "{{ repository }}"
    dest: "{{ repo_destination }}"
    force: false
    update: false
  tags: pull-repo

- name: Import daemon file to systemd.
  ansible.builtin.template:
    src: demod.service.j2
    dest: "{{ web_daemon.unit_path }}"
    mode: "644"
  tags: import-daemon-file
  notify:
    - Restart demod.

- name: Start web-daemon at boot.
  ansible.builtin.service:
    name: "{{ web_daemon.name }}"
    enabled: true
    state: started
  tags: demod-enable

- name: Import webapp-settings from template to production environment.
  ansible.builtin.template:
    src: production.yml.j2
    dest: "{{ prod_settings_destination }}"
    mode: "644"
  tags: import-prod-settings
  notify:
    - Restart demod.

- name: Flush handlers.
  ansible.builtin.meta: flush_handlers
